@startuml
class utilizatorul {}
class landing_page {}
class simple_traveler {}
class fereastra_login_register {}
class mijlocul_paginii {}
class fundalul_paginii {}
class puncte_de_atractie {}
class marele_zid_chinezesc {}
class turnul_eiffel {}
class colosseum {}
class empire_state_building {}
class parc_safari {}
class capitol_building {}
class palat_imperial_tokyo {}
class machu_picchu {}
class autentification {}
class buton_new_account {}
class dimensiunea {}
fereastra_login_register..buton_new_account
fundalul_paginii..>punct_de_atractie
class label_cu_numele_casutei
class sir_de_caractere
class noua_fereastra {}
class casuta {}
class buton_de_register {}
class e_mail {
xxxyyy@yahoo.com zzzttt@gmail.com
verifica_sir_caractere@domeniu.com()

}
class parola {
label
verifica_sir_caractere()
}
class prenume {}
class nume {}
class data_nasterii {}
class sex {
masculin,feminin
verifica_sex()
}
class combinatie {}
class semne_de_punctuatie {}
sir_de_caractere..casuta
noua_fereastra..casuta
noua_fereastra..buton_de_register
casuta -- e_mail
casuta -- parola
casuta -- prenume
casuta -- nume
casuta -- data_nasterii
casuta -- sex
@enduml